// Auto-generated by mint. Do not edit.
#pragma once

#include <string_view>

namespace scenes {


namespace models {

inline constexpr std::string_view kJustAGirl = "abf2a568-2ff3-48f6-a895-b4142500366f";
} // namespace models



} // namespace scenes
